### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by Ectalite** [MrMonk3y/texTrans#3]
Hello,

Thanks for creating this project, I saw that you didn't add a license to it and because of this under [GitHub rules](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license) it means this project is closed source.
Could you please add a license to the project ?

**Comment by MrMonk3y** [comment]
Hi there. Sure! License has been added.
